# Python Build and Deploy Pipeline
# This pipeline builds, tests, and deploys a Python Flask application.
# Customize the steps for your project's requirements.

trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
- job: Build
  displayName: 'Build and Test'
  steps:
  - script: echo Checking out the code
    displayName: 'Checkout Code'

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true
    displayName: 'Set up Python'

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install Dependencies'
    workingDirectory: ./app

  - script: |
      python -m pytest
    displayName: 'Run Tests'
    workingDirectory: ./app

- job: Deploy
  displayName: 'Deploy to Production'
  dependsOn: Build
  condition: and(succeeded(), eq(variables['Build.Reason'], 'IndividualCI'))
  steps:
  - script: echo Checking out the code
    displayName: 'Checkout Code'

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true
    displayName: 'Set up Python'

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install Dependencies'
    workingDirectory: ./app

  - script: |
      # Replace these commands with your actual deployment process
      echo Deploying the application...
    displayName: 'Deploy Application'
    workingDirectory: ./app
